### ISSUE TITLE
Host `odoc` documentation on gh-pages branch

### ISSUE THREAD

**Issue by anuragsoni** [ocaml-community/calendar#18]
Not sure that #15 is still relevant. Using currently release `odoc` i'm able to generate documentation using `dune build @doc`. It might be nice to have that output hosted on the gh-pages branch so it can be viewed online.

**Comment by pmetzger** [comment]
@anuragsoni Propose a pull request to do the right things?

**Comment by anuragsoni** [comment]
@pmetzger I can make a PR adding a target to the `Makefile`. I was thinking more like people with admin rights can publish docs using `dune-release`. It makes it really easy for projects using `dune`.

**Comment by anuragsoni** [comment]
@loxs now that #19 is merged, you would be able to run `dune-release distrib` and `dune-release publish doc` to have a `gh-pages` branch with the documentation files.

**Comment by loxs** [comment]
Done, documentation is here: https://ocaml-community.github.io/calendar/calendar/CalendarLib/index.html

**Comment by loxs** [comment]
I also updated the README of the master branch to point to it.

**Comment by johnwhitington** [comment]
> I also updated the README of the master branch to point to it.

README appears to still point to http://calendar.forge.ocamlcore.org/doc/ (404) in Section 6 - Documentation.

**Comment by pmetzger** [comment]
@johnwhitington Submit a PR!
