### ISSUE TITLE
3.0 Release or just merge 3.0 branch into master and make master the primary development branch?

### ISSUE THREAD

**Issue by loxs** [ocaml-community/calendar#20]
I haven't been able to spend a lot of time with calendar (and OCaml in general) for the past months. 

My initial plan was to stabilise this branch and then merge it in to master and do a 3.0 release, which would be considered backwards incompatible.

What I'm lacking right at the moment is knowledge on how to do Opam releases.

Please, anyone interested, comment on what you prefer with regards of branches and releases.
Probably @pmetzger  was right after all - continuing in master might be a good idea.

**Comment by anuragsoni** [comment]
I find having a generic rule about releases a little difficult to define. At the end of the day it should be the judgement call of the maintainer when they feel something is ready for a new release.

From a potential contributor's standpoint I don't think the actual branch names (3.0 vs master vs develop or something else altogether) is as important as having clear guidelines. It might be nicer for anyone taking a look at the repository to land on the default branch where active development occurs. I'm not sure leaving around a master branch that is a snapshot of everything before the last release is that useful. Tags can be used for viewing older release and short-lived branches created from a tag can be used if there is a bug-fix release required. Maintaining multiple branches `3.0, <future version>`, etc might makes things a little confusing if there is no clear indication about which branch should actually be used.

As for the `opam` release process, i'm sure folks here will be happy to help if you have any questions :smile: 

I'd try to use tools like `dune-release` as much as you can to make the maintainer's life easier (If there are issues you face while using such tools, then that will be good feedback for people working on `dune-release` too)

**Comment by c-cube** [comment]
I think the simplest is to merge back into master and then do a 3.0 release (assuming issues blocking 3.0 are fixed, if there's any).

**Comment by tcoopman** [comment]
Is there any progress on this? Is it recommend to use the 3.0 branch?

**Comment by pmetzger** [comment]
@tcoopman I doubt any progress has been made.

**Comment by loxs** [comment]
Yeah, although I use the 3.0 branch in production, I use it only for recent dates (and not datetimes) and can't guarantee that other parts of the functionality work.

**Comment by pmetzger** [comment]
@loxs You took on maintaining this. My suggestion is that if you don't have time to do it, you should pass the baton on to someone else.

**Comment by loxs** [comment]
@pmetzger more than happy to do it.

**Comment by pmetzger** [comment]
I'd solicit on discuss.ocaml.org...

**Comment by kit-ty-kate** [comment]
Fixed by #41
