### ISSUE TITLE
opam release?

### ISSUE THREAD

**Issue by jeromesimeon** [ocaml-community/calendar#23]
I may have missed it, but I couldn't find this new version of Calendar on opam. Is there any plan to release it in the foreseeable future? I'm particularly interested in the switch from Str to Re...

**Comment by pmetzger** [comment]
I think what's in the git repo right now is a bit of a mess, especially because it isn't clear if the tip of development is the trunk or the most recent branch. We'd probably be happy to have someone else take over maintenance.

**Comment by jeromesimeon** [comment]
Thanks for the response.

I was just looking at 3x and it seems to at least: compile/pass tests. I couldn't entirely tell whether there were any major new features of if it was mostly a maintenance / upgrade release. I'm assuming the original developer (@signoles ?) is not in a position to step in?

**Comment by pmetzger** [comment]
And unfortunately the person who took it on (loxs) is not in a position to fix things.

**Comment by jeromesimeon** [comment]
I see. Ok thanks for the clarification.

**Comment by pmetzger** [comment]
But again, if someone else was interested in taking over maintenance, they would probably be very welcome indeed.

**Comment by jeromesimeon** [comment]
I don't think I have the cycles to sign up for that. I could possibly help on a release in a discrete way.

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/ocaml/opam-repository/pull/22242
