### ISSUE TITLE
binaries contain build date

### ISSUE THREAD

**Issue by olafhering** [ocaml-community/calendar#27]
PR #6 created a `src/dune` which calls `date(1)`, see commit 486d1801f16fcb439be1549de873cf90aa5f28b0
Storing a random date in binaries was never a good idea, in any project, at any time.

Debian sells a feature called ["reproducible build"](https://reproducible-builds.org/), [openSUSE/build-compare](https://github.com/openSUSE/build-compare) just wants to avoid needless republish to reduce load on mirrors.

Please, remove the version.ml:date API. It can not possibly serve any useful purpose...

**Comment by pmetzger** [comment]
Can you submit a patch to do this? It's more likely we will commit a pull request than that someone will get to it quickly on their own...

**Comment by olafhering** [comment]
Are you ok with removing that property from the API?
