### ISSUE TITLE
New release for OCaml 5.0 support

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-community/calendar#42]
Hi, currently no release of `calendar` work on OCaml 5.0 (see https://github.com/ocaml/opam-repository/pull/22208) but `master` compiles just fine.

Any chance someone could do a release of `calendar` to add support for OCaml 5.0 ?

**Comment by pmetzger** [comment]
@kit-ty-kate Would you be willing to do a release? I'd have no objection.

**Comment by kit-ty-kate** [comment]
Done https://github.com/ocaml/opam-repository/pull/22242
