### ISSUE TITLE
add OPAM files

### ISSUE THREAD

**Issue by pmetzger** [ocaml-community/calendar#5]
Right now, I believe the CI is failing because of the lack of an OPAM file. One should be added. It won't take much effort once the dune migration @c-cube is doing is done.

**Comment by anuragsoni** [comment]
Just a note that it should be using the 2.0 format.

**Comment by anuragsoni** [comment]
Some useful info if someone hasn't packaged for opam before:

* https://opam.ocaml.org/doc/Packaging.html 
* `opam lint <file.opam> verifies if the specification is compliant with what opam expects (I only found out about this yesterday)
